name: dart-chrome-app
description: A sample Dart Chrome packaged application
dependencies:
  chrome: '>=0.6.1 <0.7.0'
  polymer: '>=0.15.1 <0.16.0'
transformers:
- polymer:
    entry_points: web/index.html
    csp: true
